#ifndef _ALTERA_MEMORYDMA_M_WRITE_H_
#define _ALTERA_MEMORYDMA_M_WRITE_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'MemoryDMA' and devices
 * connected to the following master:
 *   m_write
 * This master belong to master group 'MemoryDMA_m_write'
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for module 'MemoryDMA', class 'altera_avalon_sgdma'.
 * The macros have no prefix.
 */
#define ADDRESS_WIDTH 32
#define ALWAYS_DO_MAX_BURST 1
#define ATLANTIC_CHANNEL_DATA_WIDTH 4
#define AVALON_MM_BYTE_REORDER_MODE 0
#define BURST_DATA_WIDTH 8
#define BURST_TRANSFER 0
#define BYTES_TO_TRANSFER_DATA_WIDTH 16
#define CHAIN_WRITEBACK_DATA_WIDTH 32
#define COMMAND_FIFO_DATA_WIDTH 104
#define CONTROL_DATA_WIDTH 8
#define CONTROL_SLAVE_ADDRESS_WIDTH 4
#define CONTROL_SLAVE_DATA_WIDTH 32
#define DESCRIPTOR_READ_BURST 0
#define DESC_DATA_WIDTH 32
#define HAS_READ_BLOCK 1
#define HAS_WRITE_BLOCK 1
#define IN_ERROR_WIDTH 0
#define OUT_ERROR_WIDTH 0
#define READ_BLOCK_DATA_WIDTH 32
#define READ_BURSTCOUNT_WIDTH 4
#define STATUS_TOKEN_DATA_WIDTH 24
#define STREAM_DATA_WIDTH 32
#define UNALIGNED_TRANSFER 0
#define WRITE_BLOCK_DATA_WIDTH 32
#define WRITE_BURSTCOUNT_WIDTH 4

/*
 * Macros for device 'onchip_memory2_1', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY2_1_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY2_1_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_1_COMPONENT_NAME onchip_memory2_1
#define ONCHIP_MEMORY2_1_BASE 0x20000
#define ONCHIP_MEMORY2_1_SPAN 65536
#define ONCHIP_MEMORY2_1_END 0x2ffff
#define ONCHIP_MEMORY2_1_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_1_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_1_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_1_DUAL_PORT 0
#define ONCHIP_MEMORY2_1_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_1_INIT_CONTENTS_FILE soc_system_onchip_memory2_1
#define ONCHIP_MEMORY2_1_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_1_INSTANCE_ID NONE
#define ONCHIP_MEMORY2_1_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_1_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_1_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY2_1_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_1_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_1_SIZE_VALUE 65536
#define ONCHIP_MEMORY2_1_WRITABLE 1
#define ONCHIP_MEMORY2_1_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY2_1_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY2_1_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY2_1_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY2_1_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY2_1_MEMORY_INFO_MEM_INIT_DATA_WIDTH 64
#define ONCHIP_MEMORY2_1_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory2_1

/*
 * Macros for device 'myBus', class 'altera_avalon_pio'
 * The macros are prefixed with 'MYBUS_'.
 * The prefix is the slave descriptor.
 */
#define MYBUS_COMPONENT_TYPE altera_avalon_pio
#define MYBUS_COMPONENT_NAME myBus
#define MYBUS_BASE 0x30000
#define MYBUS_SPAN 16
#define MYBUS_END 0x3000f
#define MYBUS_BIT_CLEARING_EDGE_REGISTER 0
#define MYBUS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MYBUS_CAPTURE 0
#define MYBUS_DATA_WIDTH 8
#define MYBUS_DO_TEST_BENCH_WIRING 0
#define MYBUS_DRIVEN_SIM_VALUE 0
#define MYBUS_EDGE_TYPE NONE
#define MYBUS_FREQ 2000000
#define MYBUS_HAS_IN 0
#define MYBUS_HAS_OUT 1
#define MYBUS_HAS_TRI 0
#define MYBUS_IRQ_TYPE NONE
#define MYBUS_RESET_VALUE 0


#endif /* _ALTERA_MEMORYDMA_M_WRITE_H_ */
