#ifndef _ALTERA_MM_CLOCK_CROSSING_BRIDGE_0_H_
#define _ALTERA_MM_CLOCK_CROSSING_BRIDGE_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'mm_clock_crossing_bridge_0' and devices
 * connected to the following master:
 *   m0
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'myBus', class 'altera_avalon_pio'
 * The macros are prefixed with 'MYBUS_'.
 * The prefix is the slave descriptor.
 */
#define MYBUS_COMPONENT_TYPE altera_avalon_pio
#define MYBUS_COMPONENT_NAME myBus
#define MYBUS_BASE 0x0
#define MYBUS_SPAN 16
#define MYBUS_END 0xf
#define MYBUS_BIT_CLEARING_EDGE_REGISTER 0
#define MYBUS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MYBUS_CAPTURE 0
#define MYBUS_DATA_WIDTH 8
#define MYBUS_DO_TEST_BENCH_WIRING 0
#define MYBUS_DRIVEN_SIM_VALUE 0
#define MYBUS_EDGE_TYPE NONE
#define MYBUS_FREQ 2000000
#define MYBUS_HAS_IN 0
#define MYBUS_HAS_OUT 1
#define MYBUS_HAS_TRI 0
#define MYBUS_IRQ_TYPE NONE
#define MYBUS_RESET_VALUE 0


#endif /* _ALTERA_MM_CLOCK_CROSSING_BRIDGE_0_H_ */
