// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Mon Apr 08 02:10:45 2024

PLL PLL_inst
(
	.refclk(refclk_sig) ,	// input  refclk_sig
	.rst(rst_sig) ,	// input  rst_sig
	.outclk_0(outclk_0_sig) ,	// output  outclk_0_sig
	.outclk_1(outclk_1_sig) ,	// output  outclk_1_sig
	.outclk_2(outclk_2_sig) ,	// output  outclk_2_sig
	.locked(locked_sig) 	// output  locked_sig
);

